// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_1.Models;

namespace Project_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231008111655_createdb")]
    partial class createdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project_1.Models.Diziler", b =>
                {
                    b.Property<int>("diziNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("CalisanSayisi")
                        .HasColumnType("int");

                    b.Property<decimal>("Sermaye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Yetkili")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("diziNo");

                    b.ToTable("Dizilers");
                });

            modelBuilder.Entity("Project_1.Models.Oyuncular", b =>
                {
                    b.Property<int>("OyuncuNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiziNo")
                        .HasColumnType("int");

                    b.Property<decimal>("Maas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OyuncuNo");

                    b.HasIndex("DiziNo");

                    b.ToTable("Oyunculars");
                });

            modelBuilder.Entity("Project_1.Models.Oyuncular", b =>
                {
                    b.HasOne("Project_1.Models.Diziler", "Dizi")
                        .WithMany()
                        .HasForeignKey("DiziNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dizi");
                });
#pragma warning restore 612, 618
        }
    }
}
