//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garage_webApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisan
    {
        public int CalisanNo { get; set; }
        public string CalisanAdSoyad { get; set; }
        public Nullable<int> CalisanYas { get; set; }
        public string CalisanUnvan { get; set; }
        public Nullable<int> SubeNo { get; set; }
    
        public virtual Sube Sube { get; set; }
    }
}
