// <auto-generated />
using Data_Access_Layer.Concreate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data_Access_Layer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Models.Lig1", b =>
                {
                    b.Property<int>("LigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LigAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LigDeger")
                        .HasColumnType("int");

                    b.Property<int>("LigIzleyciSay")
                        .HasColumnType("int");

                    b.Property<string>("LigResim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LigTakimSay")
                        .HasColumnType("int");

                    b.Property<string>("UlkeAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LigID");

                    b.ToTable("Lig1s");
                });

            modelBuilder.Entity("EntityLayer.Models.Oyuncu1", b =>
                {
                    b.Property<int>("OyuncuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OyuncuAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OyuncuMevki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OyuncuResim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OyuncuYas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TakimID")
                        .HasColumnType("int");

                    b.HasKey("OyuncuId");

                    b.HasIndex("TakimID");

                    b.ToTable("Oyuncu1s");
                });

            modelBuilder.Entity("EntityLayer.Models.Takim1", b =>
                {
                    b.Property<int>("TakimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LigID")
                        .HasColumnType("int");

                    b.Property<string>("TakimAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TakimDeger")
                        .HasColumnType("int");

                    b.Property<int>("TakimOyunSay")
                        .HasColumnType("int");

                    b.Property<string>("TakimResim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TakimID");

                    b.HasIndex("LigID");

                    b.ToTable("Takim1s");
                });

            modelBuilder.Entity("EntityLayer.Models.Oyuncu1", b =>
                {
                    b.HasOne("EntityLayer.Models.Takim1", "Takim")
                        .WithMany()
                        .HasForeignKey("TakimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Takim");
                });

            modelBuilder.Entity("EntityLayer.Models.Takim1", b =>
                {
                    b.HasOne("EntityLayer.Models.Lig1", "Lig")
                        .WithMany()
                        .HasForeignKey("LigID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lig");
                });
#pragma warning restore 612, 618
        }
    }
}
