//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelfirstproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int studentID { get; set; }
        public string studentNameSurname { get; set; }
        public int studentAge { get; set; }
        public string studentPhone { get; set; }
        public string studentAdres { get; set; }
        public int teacherID { get; set; }
    }
}
