//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelfirstproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public int teacherID { get; set; }
        public string teacherNameSurname { get; set; }
        public decimal teacherWage { get; set; }
        public string teacherBranch { get; set; }
        public string teacherMail { get; set; }
    }
}
