//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarProje_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int MusteriNo { get; set; }
        public string MusteriAd { get; set; }
        public Nullable<int> MusteriYas { get; set; }
        public string MusteriSehir { get; set; }
        public Nullable<int> AracNo { get; set; }
    
        public virtual Araclar Araclar { get; set; }
    }
}
