//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        public int calisanID { get; set; }
        public string calisanAdSoyad { get; set; }
        public string calisanSifre { get; set; }
        public string calisanAdres { get; set; }
        public string calisanGorev { get; set; }
        public int kutuphaneID { get; set; }
    
        public virtual Kutuphane Kutuphane { get; set; }
    }
}
