//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace user_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calisan
    {
        public int calisanNo { get; set; }
        public string calisanAdSoyad { get; set; }
        public string calisanAdres { get; set; }
        public string calisanTel { get; set; }
        public int depertmanNo { get; set; }
    }
}
