//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace user_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class depertman
    {
        public int depertmanNo { get; set; }
        public string depertmanAd { get; set; }
        public string depertmanAdres { get; set; }
        public string depertmanTel { get; set; }
        public int firmaNo { get; set; }
    }
}
