//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace user_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plaza
    {
        public int plazaNo { get; set; }
        public string plazaAd { get; set; }
        public string plazaAdres { get; set; }
        public string plazaTel { get; set; }
    }
}
