//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GarageEntities : DbContext
    {
        public GarageEntities()
            : base("name=GarageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Araclar> Araclars { get; set; }
        public virtual DbSet<Calisan> Calisans { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
        public virtual DbSet<Sube> Subes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
