//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model_first.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int UrunNo { get; set; }
        public string UrunAdi { get; set; }
        public int Fiyat { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public int PersonelNo { get; set; }
    }
}
