//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMvcProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Davalar
    {
        public int DavaNo { get; set; }
        public string DavaAdi { get; set; }
        public string DosyaNo { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string Aciklama { get; set; }
        public string AdliyeAdi { get; set; }
        public string AdliyeAdres { get; set; }
        public string DavaTipi { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
