//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baukolej.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmenler
    {
        public int ogretmenNo { get; set; }
        public string adSoyad { get; set; }
        public string brans { get; set; }
        public string mail { get; set; }
        public Nullable<decimal> maas { get; set; }
    }
}
