//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baukolej.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        public int ogrenciNo { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<System.DateTime> DogumTarih { get; set; }
        public Nullable<bool> BursDurumu { get; set; }
        public string Adres { get; set; }
        public bool Cinsiyet { get; set; }
        public Nullable<int> okulNo { get; set; }
    
        public virtual Okul Okul { get; set; }
    }
}
