//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baukolej.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Okul
    {
        public int okulNo { get; set; }
        public string Adi { get; set; }
        public string Adres { get; set; }
        public string Mudur { get; set; }
    }
}
